Bookers/config/routes.rb
Rails.application.routes.draw do
	root 'homes#top'
	get '/home/about' => 'abouts#top'
	devise_for :users, controllers: {
	  sessions: 'users/sessions',
	  registrations: 'users/registrations'
	}
	resources :users
	resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum: 200 }
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @template = Book.new
  end

  def create
    @books = Book.all
    @template = Book.new(book_params)
    @template.user_id = current_user.id
    if @template.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@template)
    else
      render 'index'
    end
  end

  def index
   @books = Book.all
   @template = Book.new
 end

 def show
   @book = Book.find(params[:id])
   @user = Book.find(params[:id]).user
   @template = Book.new
 end

 def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
 end

 def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book)
    flash[:notice] = 'Book was successfully updated.'
  else
    render 'edit'
  end
end

def destroy
 @book = Book.find(params[:id])
 @book.destroy
 redirect_to books_path
end

private
def book_params
 params.require(:book).permit(:title,:body)
end

def user_params
  params.require(:user).permit(:name,:introduction,:profile_image)
end
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <h2><%= @book.errors.count %>error</h2>
      <div>
       <ul>
        <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= form_for(@book) do |f| %>

    <p>Title</p>
    <p><%= f.text_field :title,class:"form-control" %></p>

    <p>Opinion</p>
    <p><%= f.text_area :body,class:"form-control" %></p>


    <%= f.submit "Update Book",class:"btn btn-primary btn-block" %>

    <% end %>

    <%= link_to "Show",book_path(@book) %>
    |
    <%= link_to "Back",books_path %>
  </div>
  <div class="col-lg-3"></div>
</div>
</div>

Bookers/app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'template/template', template: @template, user: current_user %>
		</div>
		<div class="col-xs-9">
			<h1>Books</h1>
			<div>
				<table class="table">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>

					<tbody>
						<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to book.user do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
								<% end %>
							</td>
							<td><%= link_to book.title,book_path(book) %></td>
							<td><%= book.body %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

Bookers/app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<% if flash[:notice] %>
		<p><%= flash[:notice] %></p>
		<% end %>
		<div class="col-xs-3">>
			<%= render 'template/template', template: @template, user: @user %>
		</div>
		<div class="col-xs-9">
			<h1>Book detail</h1>
			<div>
				<table class="table">
					<tbody>
						<tr>
							<td>
								<%= link_to user_path(@user) do %>
								<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
								<%= @user.name %>
								<% end %>
							</td>
							<td><%= link_to @book.title,book_path(@book) %></td>
							<td><%= @book.body %></td>
							<% if @book.user == current_user %>
							<td><%= link_to "Edit",edit_book_path(@book) %></td>
							<td><%= link_to "Destroy",book_path(@book),method: :delete,"data-confirm" => "本当に消しますか？" %></td>
							<% end %>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>