Bookers/config/routes.rb
Rails.application.routes.draw do
	root 'homes#top'
	get '/home/about' => 'abouts#top'
	devise_for :users, controllers: {
	  sessions: 'users/sessions',
	  registrations: 'users/registrations'
	}
	resources :users
	resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <header>

    <% if user_signed_in? %>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <h3 class="header-title">Bookers</h3>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", user_path(current_user.id),class:"glyphicon glyphicon-home" %></li>
          <li><%= link_to "Users", users_path,class:"glyphicon glyphicon-user" %></li>
          <li><%= link_to "Books", books_path,class:"glyphicon glyphicon-book" %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out" %></li>
        </ul>
      </div>
    </nav>

    <% else %>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <h3 class="header-title">Bookers</h3>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",root_path,class:"glyphicon glyphicon-home"  %></li>
          <li><%= link_to "About",home_about_path,class:"glyphicon glyphicon-link" %></li>
          <li><%= link_to "sign up",new_user_registration_path,class:"glyphicon glyphicon-edit" %></li>
          <li><%= link_to "login",new_user_session_path,class:"glyphicon glyphicon-log-in" %></li>
        </ul>
      </div>
    </nav>

    <% end %>
  </header>
  <%= yield %>
  <footer class="footer-text">
    <p>CopyRight Infratop.inc</p>
  </footer>
</body>
</html>